### ISSUE TITLE
[FEATURE] ARM support for linux/macOS

### ISSUE THREAD

**Issue by PaRkThEcAr** [treysu/letterboxd-plex-sync#5]
Morning! it seems the docker image is lacking ARM support

```
╭─ ~/Dock/plex-letterboxd-sync         ✔  parkthecar@server  07:49:24 AM ─╮
╰─ docker compose up -d                                                      ─╯
WARN[0000] /Users/parkthecar/DockerStuff/plex-letterboxd-sync/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 0/1
 ⠋ letterboxd-plex-sync Pulling                                            1.0s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```

here is the docker-compose i am using
```
version: "3"
services:
  letterboxd-plex-sync:
    image: treysu/letterboxd-plex-sync:latest
    container_name: letterboxd-plex-sync
    restart: unless-stopped
    env_file:
      - ./letterboxd.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./resources:/app/resources:rw
```
